Localized text comparison
mattzollinhofer/vue-typeahead-bootstrap pull request #100
Opened 2020-12-26 14:05 UTC by aeyoll

Hello, french guy here needing to work with accentuated words! I made fixes from PR #85. Now, the sort order is preserved and accentuated word are correctly highlighted. Cheers!

2020-12-28 20:07 UTC, mattzollinhofer requested changes
Thanks so much for improving the PR!!! I think this is really close!

I was a little surprised to see the big map and honestly I'm nervous about the maintenance of that map, it feels very fragile and problematic. At the very least, we need a number of tests around the character looping part and the `highlight` method to make sure we don't break this in the future.

Thanks again!

2020-12-28 20:07 UTC, mattzollinhofer commented on src/components/VueTypeaheadBootstrapList.vue
> +        }
If this needs to stay, can you pull this out into its own method? It seems like it deserves it's own name and a few tests demonstrating it's purpose.

2020-12-28 20:07 UTC, mattzollinhofer commented on src/components/VueTypeaheadBootstrapList.vue
> +          const bIndex = normalizedTextB.indexOf(normalizedTextB.match(re)[0])
Yeah, I think this will preserve the order, thanks!

2020-12-28 20:07 UTC, mattzollinhofer commented on tests/unit/VueTypeaheadBootstrapList.spec.js
> +  it("Orders the results with text matches early in the hit's text first, not alphabetically (with accents)", () => {
I really appreciate this test, definitely helps see what's going on.

2020-12-28 21:39 UTC, aeyoll commented on src/components/VueTypeaheadBootstrapList.vue
> +const characterMap = new Map([
Yeah, I'm not so sure about it either, but I don't know how I can do it otherwise. The map was adapted from the Stack Overflow post you linked (using a native Map instead of an array of objects).

The map defines a list of unicode characters derived from a letter. For exemple, for "e", derived letters can be : `[eⓔｅèéêềếễểẽēḕḗĕėëẻěȅȇẹệȩḝęḙḛɇɛǝ]`

The idea is to be able to highlight part of a word with an accent in the list, regardless of the accent typed (or not!) in the query. Please look at this exemple I made: https://regex101.com/r/9ABUaR/1/ (in the loop I made, every letter from the map is replaced, but I just changed one here for readability).If I have "secrétaire" in my list, I want it to be highlighted if I type "secre", "secré" or "secrè"

2020-12-29 03:06 UTC, mattzollinhofer approved these changes
I'm going to merge this manually so I can add some release information, so I'll end up closing this PR, but this was awesome. Thank you! I know a number of folks will appreciate this!

2020-12-29 03:06 UTC, mattzollinhofer commented on src/components/VueTypeaheadBootstrapList.vue
> +const characterMap = new Map([
Wow, yeah. Thanks for the more detailed info and the test. I love it and I hate it. I can't think of any better ideas either for now so let's roll with it. I'm merging this in and hoping someone comes along with a super clean version of this :-)

Thanks again for the help, the regex101 link helped clarify it even more. Appreciate it.

2020-12-29 03:29 UTC, mattzollinhofer commented
Merged this in with release v.2.6.1. Thanks again for the help!!!

2020-12-29 03:29 UTC, closed without merging

2020-12-29 06:48 UTC, aeyoll commented
> Merged this in with release v.2.6.1. Thanks again for the help!!!

You're welcome, thank you!